// AUTH ACTION TYPES
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
// DECISION ACTION TYPES
export const SET_USER_DECISIONS = 'SET_USER_DECISIONS';
export const SET_PUBLIC_DECISIONS = 'SET_PUBLIC_DECISIONS';
export const SET_DECISION = 'SET_DECISION';
export const REMOVE_DECISION = 'REMOVE_DECISION';
export const ADD_USER_DECISION = 'ADD_USER_DECISION';
export const ADD_PUBLIC_DECISION = 'ADD_PUBLIC_DECISION';
export const REMOVE_PUBLIC_DECISION = 'REMOVE_PUBLIC_DECISION';
// OPTION ACTION TYPES
export const SET_DECISION_OPTIONS = 'SET_DECISION_OPTIONS';
export const SET_OPTION = 'SET_OPTION';
export const ADD_DECISION_OPTION = 'ADD_DECISION_OPTION';
export const REMOVE_OPTION = 'REMOVE_OPTION';
